import type { MediaCatalogRecord } from '@/types/media';

export const catalog: MediaCatalogRecord[] = [
  {
    id: 'clouds-rest',
    title: 'Where the Clouds Rest',
    synopsis: 'A quiet cartographer follows a ribbon of light across islands that only appear at dawn.',
    coverPoster: '/posters/aurora.jpg',
    genre: 'Fantasy',
    year: 2025,
    format: 'Series · 12 episodes',
    episodes: [{ episodeNumber: 1, episodeTitle: 'The First Map', mirrors: [] }],
  },
  {
    id: 'tideglass',
    title: 'Tideglass',
    synopsis: 'On the edge of a rose-coloured sea, two siblings learn to read the weather in the water.',
    coverPoster: '/posters/tideglass.jpg',
    genre: 'Coming of age',
    year: 2024,
    format: 'Film · 1h 48m',
    episodes: [{ episodeNumber: 1, episodeTitle: 'Feature', mirrors: [] }],
  },
  {
    id: 'sky-archive',
    title: 'The Sky Archive',
    synopsis: 'A young keeper catalogs the changing colours of a city at the foot of an old mountain.',
    coverPoster: '/posters/skyarchive.jpg',
    genre: 'Slice of life',
    year: 2025,
    format: 'Series · 8 episodes',
    episodes: [{ episodeNumber: 1, episodeTitle: 'Evening Index', mirrors: [] }],
  },
  {
    id: 'mist-isles',
    title: 'Isles Between Worlds',
    synopsis: 'A drifting garden, a hand-written invitation, and a journey with no fixed destination.',
    coverPoster: '/posters/mist-isles.jpg',
    genre: 'Adventure',
    year: 2023,
    format: 'Series · 10 episodes',
    episodes: [{ episodeNumber: 1, episodeTitle: 'A Green Horizon', mirrors: [] }],
  },
  {
    id: 'moon-tide',
    title: 'A Moon Above the Quiet Sea',
    synopsis: 'A lighthouse apprentice discovers that the moon has been keeping a second tide.',
    coverPoster: '/posters/moon-tide.jpg',
    genre: 'Science fantasy',
    year: 2024,
    format: 'Film · 1h 36m',
    episodes: [{ episodeNumber: 1, episodeTitle: 'Feature', mirrors: [] }],
  },
];
